### ISSUE TITLE
Target URI doesn't exit.

### ISSUE THREAD

**Issue by dulkith** [brianegan/font_awesome_flutter#34]
`import 'package:font_awesome_flutter/font_awesome_flutter.dart';`

> Target URI doesn't exit.

I added dependencies like this:

```
dependencies:
  flutter:
    sdk: flutter
    font_awesome_flutter: 8.4.0
```

**Comment by dulkith** [comment]
```
dependencies:
  flutter:
    sdk: flutter
font_awesome_flutter: 8.4.0
```
Fixed like this.
